name: 部署博客网站

# 表示什么时候触发部署
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 安装Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.2'
          extended: true

      - name: 生成public文件夹
        run: hugo

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public